### ISSUE TITLE
release

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_recovery_behaviours#10]
This is an unreleased  part of the marathon system, so it needs to be released asap.

**Comment by bfalacerda** [comment]
i have it almost ready for release, will finish on Monday

**Comment by bfalacerda** [comment]
After #12 is merged we can start the release process

**Comment by bfalacerda** [comment]
ready to start the release process. @marc-hanheide can you give me a hand?

**Comment by bfalacerda** [comment]
released
