### ISSUE TITLE
[backtrack_behaviour] PTU is not reset to the correct position after the backtrack behaviour

### ISSUE THREAD

**Issue by ghost** [strands-project/strands_recovery_behaviours#19]
After the backtrack behavior is executed, the PTU returns to the front facing state, but a small misalignment remains, causing the head xtion to be slightly tilted to one side. We were only really able to fix this by resetting the PTU (turning the controller for the PTU off and on again). This seems to screw with the docking and I suspect also with other components that use the head camera like the pan-tilt sweep. 

I thought it might be that the 'ptu_goal.pan = 179' cannot be reached but is still set as actual position and that then turning back to '0' actually causes it to overshoot, however it is actually not turned back enough and remains at angle of '~5'. @BFALacerda @nilsbore any thoughts?

**Comment by nilsbore** [comment]
Hmm, I haven't noticed this but that seems like a likely explanation for your problem. I don't observe that behaviour on our robot. Could it be that the drivers have changed again?

**Comment by ghost** [comment]
Well we didn't change anything and the pantilt package in the scitos_driver repo didn't change in a long time.

**Comment by nilsbore** [comment]
Ok, I'll try to replicate tomorrow morning
Den 18 nov 2014 18:37 skrev "Alexander Hermans" notifications@github.com:

**Comment by lucasb-eyer** [comment]
See strands-project/scitos_drivers#87

**Comment by nilsbore** [comment]
I can confirm the issue here, will see how low the pan has to be not to offset the stepper.

**Comment by nilsbore** [comment]
Should be fixed now. @lucasb-eyer Ok to close this?

**Comment by lucasb-eyer** [comment]
Yeah didn't observe this anymore, we can always reopen if it happens again, reproducibly.
