### ISSUE TITLE
[backtrack_behaviour] Running people over.

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_recovery_behaviours#26]
Just from testing it a few times I noticed that the behaviour is flawed if someone is too close to the camera, i.e. standing directly behind the robot, and that the robot just drives back regardless. This will run over kids and adults in public areas and could be a problem. One way of fixing this would be to let the robot say something and show a website to make people aware before driving back (while the PTU turns?!) and possibly don't attempt the behaviour that quickly because there will be people blocking the robot quite often.

**Comment by bfalacerda** [comment]
the most recent nav recovery has an extra sleep time and a costmap clearance before trying to do any backtracking, so it takes more time for the robot to start moving backwards (at least 10 to 15 seconds). I can also add some speech and text in the screen to it easily, will do it later today/tomorrow, depending on how fast we're able to get everything running in the library here

**Comment by cdondrup** [comment]
Sounds good, let me know if I can help testing.

**Comment by bfalacerda** [comment]
you can already see if it takes enough time to start backtracking (needs a release of this repo and of strands_navigation)

**Comment by cdondrup** [comment]
Will trigger a release

**Comment by bfalacerda** [comment]
this is done, the robot now waits for more time before triggering backtrack, and also says it's going to do it
