### ISSUE TITLE
Help tweet is over character limit

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_recovery_behaviours#34]
Another lack of testing revealed!

```
[INFO] [WallTime: 1416831874.846528] /strands_tweets: Tweeting I've been having some issue going around for quite some time now. I'm sure I'm pretty stuck somewhere. What does it │························
look like?                                                                                                                                                                         │························[INFO] [WallTime: 1416831874.847257] Tweeting I've been having some issue going around for quite some time now. I'm sure I'm pretty stuck somewhere. What does it look like? ... (1│························
26)                                                                                                                                                                                │························
Twitter API returned a 403 (Forbidden), Status is over 140 characters. 
```

**Comment by bfalacerda** [comment]
ah! does that kill anything? I'll make the strings shorter after the lecture

**Comment by bfalacerda** [comment]
https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/strands_human_help/src/strands_human_help/help_tweet.py#L32

They're here in case someone wants to change them

**Comment by hawesie** [comment]
Non-fatal.

**Comment by bfalacerda** [comment]
It's just 126 characters though. Are we adding hashtags to it?

**Comment by Jailander** [comment]
You can set the force parameter on the Twitter action server to publish more than a 140 characters in as many status as needed

-------- Mensaje original --------
De: Nick Hawes
Fecha:24/11/2014 12:30 PM (GMT+00:00)
Para: strands-project/strands_recovery_behaviours
Asunto: [strands_recovery_behaviours] Help tweet is over character limit (#34)

Another lack of testing revealed!

[INFO] [WallTime: 1416831874.846528] /strands_tweets: Tweeting I've been having some issue going around for quite some time now. I'm sure I'm pretty stuck somewhere. What does it │························
look like?                                                                                                                                                                         │························[INFO] [WallTime: 1416831874.847257] Tweeting I've been having some issue going around for quite some time now. I'm sure I'm pretty stuck somewhere. What does it look like? ... (1│························
26)                                                                                                                                                                                │························
Twitter API returned a 403 (Forbidden), Status is over 140 characters.

—
Reply to this email directly or view it on GitHubhttps://github.com/strands-project/strands_recovery_behaviours/issues/34.

The University of Lincoln, located in the heart of the city of Lincoln, has established an international reputation based on high student satisfaction, excellent graduate employment and world-class research.

The information in this e-mail and any attachments may be confidential. If you have received this email in error please notify the sender immediately and remove it from your system. Do not disclose the contents to another person or take copies.

Email is not secure and may contain viruses. The University of Lincoln makes every effort to ensure email is sent without viruses, but cannot guarantee this and recommends recipients take appropriate precautions.

The University may monitor email traffic data and content in accordance with its policies and English law. Further information can be found at: http://www.lincoln.ac.uk/legal.

**Comment by hawesie** [comment]
> On 24 Nov 2014, at 12:38, BFALacerda notifications@github.com wrote:
> 
> It's just 126 characters though. Are we adding hashtags to it?

No, but the image URL is added.

**Comment by Jailander** [comment]
ah Ok, in that case no, sorry
