### ISSUE TITLE
[walking_group_recovery] Sound is played after button is pressed and page design

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_recovery_behaviours#47]
I think the sound should be played when the first web page is shown and the page should have less text but maybe just one big button.

**Comment by nilsbore** [comment]
For me it plays directly. It should actually skip the button completely, going directly into pushing mode. I'll have a look on the actual robot since I've only tested in simulation recently.

**Comment by nilsbore** [comment]
@cdondrup Tested on Rosie and it works as expected.

**Comment by cdondrup** [comment]
OK, let's have a look in Vienna. thank you for testing!

**Comment by nilsbore** [comment]
@cdondrup Can we close this? I never had this problem?

**Comment by cdondrup** [comment]
Yes
