### ISSUE TITLE
[backtrack_behaviour] Waiting for move_base action

### ISSUE THREAD

**Issue by nilsbore** [strands-project/strands_recovery_behaviours#48]
When I run the latest navigation on Rosie, the backtrack behaviour does not start because because it's waiting for the `move_base` server at https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/backtrack_behaviour/scripts/backtrack_server.py#L32 . @bfalacerda Any ideas why?

**Comment by bfalacerda** [comment]
no clue, just the obvious: it looks like move_base isnt running?

**Comment by nilsbore** [comment]
What about this line: https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/backtrack_behaviour/scripts/backtrack_server.py#L36 ?

**Comment by nilsbore** [comment]
Or https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/backtrack_behaviour/scripts/backtrack_server.py#L40 . I saw that you changed some stuff with `strands_navfn`. Does that affect the namespaces?

**Comment by nilsbore** [comment]
I guess that it should be renamed `/strands_navfn/NavfnROS/make_plan`: https://github.com/strands-project/strands_movebase/blob/21d0cf1429f2b57cf0fbba7a401075647a21caa1/strands_movebase/strands_movebase_params/move_base_params.yaml#L1

**Comment by bfalacerda** [comment]
I dont think so. can you run strands_movebase and check the available services to see if /move_base/NavfnROS/make_plan exists?

**Comment by nilsbore** [comment]
Yes, there seems to be some other problem, move base is not started for some reason.

**Comment by nilsbore** [comment]
Ok, something else going on here, closing.
