### ISSUE TITLE
[reobserve_recovery_behaviour] Add package

### ISSUE THREAD

**Issue by nilsbore** [strands-project/strands_recovery_behaviours#6]
I have a package that needs merging, it's basically a recovery behaviour that reobserves stuff that's blocking the way and tells it to go away=).

**Comment by bfalacerda** [comment]
cool. make a PR so we can see what needs to be done to add it to the monitiored_navigation sm (I assume that's the idea)

**Comment by nilsbore** [comment]
This won't happen, too much water under the bridge ;).
