### ISSUE TITLE
merge the help_manager, help_screen and help_speech packages

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_recovery_behaviours#8]
These 3 packages were created a long time ago because we wanted to make strands_navigation independent from strands_ui (the `help_manager` stayed in strands_navigation and the others were moved to strands_ui).

The nodes launched in each package communicate via services, but now that everything is back in the same repo, I'm thinking of just creating a new `strands_human_help` package that encapsulates the functionalities of the`help_manager`, `help_screen` and `help_speech` packages, without all the service calling.

**Comment by hawesie** [comment]
I think the help manager should be back in the strands_navigation as you can't run monitored navigation without it.

**Comment by bfalacerda** [comment]
you can run the bare bone monitored navigation by doing

```
rosrun monitored_navigation monitored_nav.py 
```

Then I have a launch file specific for strands that needs the stuff in strands_recovery_behaviours, which is there just for convenience.

**Comment by hawesie** [comment]
How should we arrange the startup between these packages? I imagine future users will just try to run the topological_navigation launch file, so shall we add that bare-bones bit into that?

**Comment by bfalacerda** [comment]
maybe a topological_navigation.launch that just runs the node and a strands_topological_navigation.launch that uses the full thing? Or adding a strands argument that defaults to false to the launch files?

**Comment by bfalacerda** [comment]
the issue with monitored_navigation outside strands, is that you still have to develop monitors and recovery behaviours for your platform, plus nodes for asking help (these are also depending on strands_webserver for example). So i think we'll always have to provide a way for a random user to run it, but also keep some configurations for ourselves

**Comment by hawesie** [comment]
I agree entirely. Let's add that script to topological navigation and move the strands_monitored_navigation.launch file to this repo as it's strands-specific (removing the above node?). As the  human_help_manager package does not depend on strands stuff it can be installed separately in Ubuntu so people can use it to generate their own behaviours if necessary. In terms of the random user stuff, I'll open a new issue under nav.

**Comment by bfalacerda** [comment]
ok, i'll make the human manager part of monitored_navigation, and merge the speech and screen into a single  package

**Comment by bfalacerda** [comment]
this is done in #12
